<?php

namespace App\Http\Requests\File;

use App\Http\Requests\BaseFormRequest;

class StoreMultipleRequest extends BaseFormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'files' => 'required',
            'files.*.name' => 'required|string|max:255',
            'files.*.file' => 'required|file|max:10240',
        ];
    }

    /**
     * Returns file-related attributes excluding name and path.
     */
    public function autoGeneratedAttributes(): array
    {
        $files = $this->file('files');
        $attributes = [];

        foreach ($files as $uploadedFile) {
            $attributes[] = [
                'type'          => explode('/', $uploadedFile->getMimeType())[0],
                'size'          => $uploadedFile->getSize(),
                'mime_type'     => $uploadedFile->getMimeType(),
                'extension'     => $uploadedFile->getClientOriginalExtension(),
                'original_name' => $uploadedFile->getClientOriginalName(),
                'user_id'       => auth()->id(),
                'created_by'    => auth()->id(),
            ];
        }

        return $attributes;
    }
}
