<?php

namespace App\Http\Requests\File;

use App\Http\Requests\BaseFormRequest;

class UpdateRequest extends BaseFormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|string|max:255',
            'file' => 'required|file|max:10240',
        ];
    }

    /**
     * Returns file-related attributes excluding name and path.
     */
    public function autoGeneratedAttributes(): array
    {
        /** @var UploadedFile $uploadedFile */
        $uploadedFile = $this->file('file');

        return [
            'type'          => explode('/', $uploadedFile->getMimeType())[0],
            'size'          => $uploadedFile->getSize(),
            'mime_type'     => $uploadedFile->getMimeType(),
            'extension'     => $uploadedFile->getClientOriginalExtension(),
            'original_name' => $uploadedFile->getClientOriginalName(),
            'user_id'       => auth()->id(),
            'created_by'    => auth()->id(),
        ];
    }
}
