<?php

namespace App\Http\Controllers\Api\V1\File;

use App\Http\Controllers\ApiBaseController;
use App\Http\Requests\File\UpdateRequest;
use App\Http\Requests\File\StoreRequest;
use App\Models\File;
use App\Models\Product;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class FileController extends ApiBaseController
{
    /**
     * List files.
     */
    public function index(Request $request): JsonResponse
    {
        $files = File::query();

        $files = $files->paginate($request->input('per_page', 10));

        return $this->okResponse(['files' => $files], __('Files retrieved successfully.'));
    }

    /**
     * Show a specific file.
     */
    public function show($id): JsonResponse
    {
        $file = File::find($id);

        if (!$file) {
            return $this->notFoundResponse(__('File not found.'));
        }

        return $this->okResponse(['file' => $file], __('File retrieved successfully.'));
    }

    /**
     * Store a new file.
     */
    public function store(StoreRequest $request): JsonResponse
    {
        DB::beginTransaction();

        try {
            $uploadedFile = $request->file('file');

            // Use the trait method to upload file
            $path = $this->uploadFile($uploadedFile, 'uploads');

            // Create the file record
            $file = File::create(array_merge([
                'name' => $request->name,
                'path' => $path,
            ], $request->autoGeneratedAttributes()));

            // Commit the transaction
            DB::commit();

            // Return the created file
            return $this->createdResponse(['file' => $file], __('File uploaded successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('File upload failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to upload file.'));
        }
    }

    /**
     * Update the specified file in storage.
     */
    public function update(UpdateRequest $request, int $id): JsonResponse
    {
        DB::beginTransaction();

        try {
            $file = File::find($id);

            if (! $file) {
                return $this->notFoundResponse(__('File not found.'));
            }

            // Handle file upload if a new file is provided
            $uploadedFile = $request->file('file');
            if ($uploadedFile) {
                if ($file->path && $this->checkExistsFile($file->path)) {
                    $this->removeFile($file->getRawOriginal('path'));
                }

                $path = $this->uploadFile($uploadedFile, 'uploads');
                $file->path = $path;
            }

            // Update the file record
            $file->update(array_merge($request->validated(), [
                'name' => $request->name,
            ]));

            // Commit the transaction
            DB::commit();

            // Return the updated file
            return $this->okResponse(['file' => $file], __('File updated successfully.'));
        } catch (\Throwable $e) {
            // Rollback the transaction in case of error
            DB::rollBack();

            // Log the error with additional context
            Log::error('File update failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'user_id' => auth()->id(),
            ]);

            // Return an error response
            return $this->serverErrorResponse([], __('Failed to update file.'));
        }
    }

    /**
     * Delete a file.
     */
    public function destroy(int $id): JsonResponse
    {
        $file = File::find($id);

        if (! $file) {
            return $this->notFoundResponse(__('File not found.'));
        }

        // Check if the file exists and remove it
        if ($file->path && $this->checkExistsFile($file->path)) {
            $this->removeFile($file->getRawOriginal('path'));
        }

        // Delete the file record
        $file->delete();

        return $this->okResponse([], __('File deleted successfully.'));
    }
}
